name: dungeon_master
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  provider: ^4.3.2+2
  http: ^0.12.2
  flutter_spinkit: ^4.1.2+1
  xml: ^4.5.1
  xml2json: ^4.4.0
  dio: ^3.0.10
  html: ^0.14.0+4
  modal_progress_hud: ^0.1.3
  cached_network_image: ^2.4.1
  shared_preferences: ^0.5.12+4
  firebase_core: "^0.5.3"
  firebase_auth: "^0.18.4+1"
  cloud_firestore: ^0.14.3+1
  flutter_datetime_picker: ^1.4.0
  intl: ^0.16.1  


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
    - assets/images/


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
